### ISSUE TITLE
Project no longer builds

### ISSUE THREAD

**Issue by rupertbg** [NewMotion/docile-charge-point#20]
Hey, sorry i'm not super great at Scala but `sbt assembly` no longer completes. Here is the log:

```
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] /Users/<username>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar:module-info.class
[error] /Users/<username>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.12.3/jackson-dataformat-cbor-2.12.3.jar:module-info.class
[error] /Users/<username>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar:module-info.class
[error] /Users/<username>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar:module-info.class
[error] 	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:143)
[error] 	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error] 	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:68)
[error] 	at sbtassembly.Assembly$.inputs$1(Assembly.scala:58)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:85)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:244)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] (lambda / assembly) deduplicate: different file contents found in the following:
[error] /Users/<username>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar:module-info.class
[error] /Users/<username>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.12.3/jackson-dataformat-cbor-2.12.3.jar:module-info.class
[error] /Users/<username>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar:module-info.class
[error] /Users/<username>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar:module-info.class
[error] Total time: 4 s, completed 18/06/2021, 11:17:31 am
```

**Comment by reinierl** [comment]
The fork at https://github.com/ihomer/docile-charge-point builds again.
